# GitHub Action for generating a contribution graph with a snake eating the contributions
name: Generate Snake

# Controls when the action will run
on:
  # This runs the job every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Generates the snake animation files
      - uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: HamoonSoleimani
          
          # The list of output files to generate
          # We'll create a dark and a light version for your README
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Pushes the generated files to the `output` branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
